//
//  CalendarGridViewModel.swift
//  GalacticCalendar
//

import Foundation

/// ViewModel for the approved monthly calendar grid.
///
/// ## Responsibilities
/// - Own grid structure from ``CalendarEngine``.
/// - Annotate days from ``EventPersistenceService`` (single source of truth).
/// - Track day selection for presentation.
///
/// ## Non-responsibilities
/// - No SwiftUI views.
/// - No direct SwiftData / ``EventRepositoryProtocol`` access.
@MainActor
@Observable
final class CalendarGridViewModel {

    // MARK: - Dependencies

    /// Reactive event catalog (single source of truth).
    private let persistenceService: EventPersistenceService

    /// Calendar used when matching events to day starts.
    private let calendar: Calendar

    // MARK: - Grid Structure

    /// Base days generated by ``CalendarEngine`` (without event annotations).
    private let baseDays: [CalendarDay]

    /// Current month obtained from the engine.
    private(set) var displayedMonth: Int

    /// Current year obtained from the engine.
    private(set) var displayedYear: Int

    // MARK: - Selection

    /// Locally selected day identifier.
    private(set) var selectedDayID: String?

    // MARK: - Lifecycle

    /// Creates a grid ViewModel for the engine's current month.
    /// - Parameters:
    ///   - persistenceService: Reactive event catalog.
    ///   - engine: Calendar structure generator.
    ///   - calendar: Calendar for day-boundary matching.
    init(
        persistenceService: EventPersistenceService,
        engine: CalendarEngine = CalendarEngine(),
        calendar: Calendar = .current
    ) {
        self.persistenceService = persistenceService
        self.calendar = calendar

        let month = engine.currentMonth()
        let year = engine.currentYear()
        let generated = Array(
            engine.generateDays(month: month, year: year)
                .prefix(CalendarConstants.monthlyGridCellCount)
        )

        self.displayedMonth = month
        self.displayedYear = year
        self.baseDays = generated
    }

    // MARK: - Derived Days

    /// Days annotated with events from the reactive catalog.
    ///
    /// Reading ``EventPersistenceService/events`` establishes Observation tracking
    /// so the grid refreshes automatically after create/update/delete.
    var annotatedDays: [CalendarDay] {
        let grouped = persistenceService.eventsGroupedByDay(in: gridDateInterval)
        return baseDays.map { day in
            let dayStart = calendar.startOfDay(for: day.date)
            return day.applyingEvents(grouped[dayStart] ?? [])
        }
    }

    /// Annotated days with the current selection flag applied.
    var presentedDays: [CalendarDay] {
        // Touch the catalog revision so Observation always tracks SSOT changes
        // even when day annotations are structurally equal.
        _ = persistenceService.eventsRevision
        return annotatedDays.map { day in
            var copy = day
            copy.isSelected = (day.id == selectedDayID)
            return copy
        }
    }

    // MARK: - Intents

    /// Selects an in-month day.
    /// - Parameter day: Tapped day.
    /// - Returns: `true` when selection was accepted.
    @discardableResult
    func selectDay(_ day: CalendarDay) -> Bool {
        guard day.isCurrentMonth else {
            return false
        }
        selectedDayID = day.id
        return true
    }

    // MARK: - Private

    /// Inclusive start / exclusive end covering every cell in the grid.
    private var gridDateInterval: DateInterval {
        guard let first = baseDays.first?.date,
              let last = baseDays.last?.date,
              let end = calendar.date(byAdding: .day, value: 1, to: last)
        else {
            let now = Date()
            return DateInterval(start: now, end: now)
        }

        return DateInterval(start: calendar.startOfDay(for: first), end: end)
    }
}
