//
//  CalendarGridViewModel.swift
//  GalacticCalendar
//

import Foundation

/// ViewModel for the approved monthly calendar grid.
///
/// ## Responsibilities
/// - Own grid structure from ``CalendarEngine``.
/// - Navigate between months (chevrons, swipe intents, year rollover).
/// - Jump to today without unnecessary recalculation.
/// - Annotate days from ``EventPersistenceService`` (single source of truth).
/// - Apply smart day selection across month/year changes (preserve or clamp).
///
/// ## Observation
/// - ``annotatedDays`` touches ``eventsRevision`` so catalog mutations refresh the grid.
/// - ``selectedDay`` / ``isShowingToday`` read ``baseDays`` only (no 42-cell rebuild).
/// - Same-period ``showMonth`` and same-ID ``selectDay`` skip invalidations.
///
/// ## Non-responsibilities
/// - No SwiftUI views.
/// - No direct SwiftData / ``EventRepositoryProtocol`` access.
/// - No ThemeManager coupling (Home coordinates title/background sync).
@MainActor
@Observable
final class CalendarGridViewModel {

    // MARK: - Dependencies

    /// Reactive event catalog (single source of truth).
    private let persistenceService: EventPersistenceService

    /// Calendar structure generator (month math + 42-cell grids).
    private let engine: CalendarEngine

    /// Calendar used when matching events to day starts.
    private let calendar: Calendar

    /// Optional shared search state (Sprint 6.7). When set, annotations honor criteria.
    private var searchViewModel: EventSearchViewModel?

    // MARK: - Grid Structure

    /// Base days generated by ``CalendarEngine`` (without event annotations).
    private var baseDays: [CalendarDay]

    /// Month currently shown in the grid (`1...12`).
    private(set) var displayedMonth: Int

    /// Year currently shown in the grid.
    private(set) var displayedYear: Int

    // MARK: - Selection

    /// Locally selected day identifier.
    private(set) var selectedDayID: String?

    /// `true` when the last period change clamped the preferred day.
    private(set) var lastSelectionWasClamped: Bool = false

    // MARK: - Lifecycle

    /// Creates a grid ViewModel for the engine's current month.
    /// - Parameters:
    ///   - persistenceService: Reactive event catalog.
    ///   - engine: Calendar structure generator.
    ///   - calendar: Calendar for day-boundary matching.
    init(
        persistenceService: EventPersistenceService,
        engine: CalendarEngine = CalendarEngine(),
        calendar: Calendar = .current
    ) {
        self.persistenceService = persistenceService
        self.engine = engine
        self.calendar = calendar

        let month = engine.currentMonth()
        let year = engine.currentYear()
        let generated = Array(
            engine.generateDays(month: month, year: year)
                .prefix(CalendarConstants.monthlyGridCellCount)
        )

        self.displayedMonth = month
        self.displayedYear = year
        self.baseDays = generated
    }

    /// Binds incremental search criteria for grid annotations.
    func bindSearch(_ searchViewModel: EventSearchViewModel?) {
        self.searchViewModel = searchViewModel
    }

    // MARK: - Derived Days

    /// Days annotated with events from the reactive catalog.
    ///
    /// Touches ``EventPersistenceService/eventsRevision`` so Observation always
    /// tracks catalog updates even when annotations are structurally equal.
    /// When search is active, only matching events annotate the grid.
    var annotatedDays: [CalendarDay] {
        _ = persistenceService.eventsRevision
        let criteria = searchViewModel?.calendarCriteria ?? EventSearchCriteria()
        if let searchViewModel {
            _ = searchViewModel.criteria
            _ = searchViewModel.appliesToCalendar
        }
        let grouped: [Date: [Event]]
        if criteria.isEmpty {
            grouped = persistenceService.eventsGroupedByDay(in: gridDateInterval)
        } else {
            grouped = persistenceService.eventsGroupedByDay(
                in: gridDateInterval,
                matching: criteria
            )
        }
        return baseDays.map { day in
            let dayStart = calendar.startOfDay(for: day.date)
            return day.applyingEvents(grouped[dayStart] ?? [])
        }
    }

    /// Annotated days with the current selection flag applied.
    var presentedDays: [CalendarDay] {
        annotatedDays.map { day in
            var copy = day
            copy.isSelected = (day.id == selectedDayID)
            return copy
        }
    }

    /// Currently selected in-month day, if any.
    ///
    /// Scans ``baseDays`` only — does not rebuild the full annotated grid.
    var selectedDay: CalendarDay? {
        guard let selectedDayID,
              let day = baseDays.first(where: { $0.id == selectedDayID && $0.isCurrentMonth }) else {
            return nil
        }
        var copy = day
        copy.isSelected = true
        return copy
    }

    /// `true` when the grid shows today's month/year and today is selected.
    var isShowingToday: Bool {
        guard engine.isCurrentPeriod(month: displayedMonth, year: displayedYear),
              let selectedDayID,
              let day = baseDays.first(where: { $0.id == selectedDayID && $0.isCurrentMonth }) else {
            return false
        }
        return day.isToday
    }

    // MARK: - Month Navigation

    /// Moves the grid to the previous calendar month (December → prior January).
    func goToPreviousMonth() {
        navigateMonth(.previous)
    }

    /// Moves the grid to the next calendar month (December → next January).
    func goToNextMonth() {
        navigateMonth(.next)
    }

    /// Applies a month navigation intent (swipe, header chevrons, animations).
    ///
    /// Uses a single ``showMonth`` transition so rapid consecutive intents never
    /// leave the grid on a partial/intermediate month. Selection is preserved or
    /// clamped by smart day selection.
    /// - Parameter intent: Direction and optional multi-month step count.
    /// - Returns: `true` when the displayed period changed.
    @discardableResult
    func navigateMonth(_ intent: CalendarMonthNavigationIntent) -> Bool {
        guard let target = engine.period(
            after: intent,
            fromMonth: displayedMonth,
            year: displayedYear
        ) else {
            return false
        }

        // Animation is owned by Presentation (`prefersAnimation` + ``Motion``).
        return showMonth(target.month, year: target.year)
    }

    /// Rebuilds the grid for an explicit month/year using smart day selection.
    ///
    /// - Keeps the selected day-of-month when it exists in the new period.
    /// - Otherwise clamps to the last valid day (31→28/29/30, leap collapse).
    /// - Skips grid regeneration when month/year are already displayed.
    /// - Parameters:
    ///   - month: Month number in `1...12`.
    ///   - year: Full year value.
    /// - Returns: `true` when the displayed period was rebuilt.
    @discardableResult
    func showMonth(_ month: Int, year: Int) -> Bool {
        guard month >= 1, month <= 12 else {
            return false
        }
        // Optimization: identical period → no full calendar recalculation.
        guard month != displayedMonth || year != displayedYear else {
            return false
        }

        let preferredDayNumber = selectedDayNumber()
        let generated = Array(
            engine.generateDays(month: month, year: year)
                .prefix(CalendarConstants.monthlyGridCellCount)
        )
        guard generated.count == CalendarConstants.monthlyGridCellCount else {
            return false
        }

        displayedMonth = month
        displayedYear = year
        baseDays = generated
        restoreSelection(preferredDayNumber: preferredDayNumber)
        return true
    }

    // MARK: - Today

    /// Jumps to the engine's current month/year and selects today.
    ///
    /// When already showing today with today selected, returns `false` and
    /// performs no grid regeneration.
    /// - Returns: `true` when the displayed period or selection changed.
    @discardableResult
    func goToToday() -> Bool {
        let targetMonth = engine.currentMonth()
        let targetYear = engine.currentYear()
        let needsGridRebuild =
            displayedMonth != targetMonth || displayedYear != targetYear

        if needsGridRebuild {
            let generated = Array(
                engine.generateDays(month: targetMonth, year: targetYear)
                    .prefix(CalendarConstants.monthlyGridCellCount)
            )
            guard generated.count == CalendarConstants.monthlyGridCellCount else {
                return false
            }
            displayedMonth = targetMonth
            displayedYear = targetYear
            baseDays = generated
            lastSelectionWasClamped = false
        }

        guard let todayCell = todayCellInCurrentGrid() else {
            return needsGridRebuild
        }

        if selectedDayID == todayCell.id && needsGridRebuild == false {
            return false
        }

        selectedDayID = todayCell.id
        return true
    }

    // MARK: - Day Selection

    /// Selects an in-month day.
    /// - Parameter day: Tapped day.
    /// - Returns: `true` when selection was accepted.
    @discardableResult
    func selectDay(_ day: CalendarDay) -> Bool {
        guard day.isCurrentMonth else {
            return false
        }
        // Same cell re-tap: accept without Observation invalidation.
        guard selectedDayID != day.id else {
            return true
        }
        selectedDayID = day.id
        lastSelectionWasClamped = false
        return true
    }

    // MARK: - Private

    /// In-month cell marked as today in the current ``baseDays`` grid.
    private func todayCellInCurrentGrid() -> CalendarDay? {
        if let marked = baseDays.first(where: { $0.isCurrentMonth && $0.isToday }) {
            return marked
        }
        let dayNumber = engine.currentDayOfMonth()
        return baseDays.first {
            $0.isCurrentMonth && $0.dayNumber == dayNumber
        }
    }

    /// Day-of-month for the current selection, if any.
    private func selectedDayNumber() -> Int? {
        guard let selectedDayID,
              let day = baseDays.first(where: { $0.id == selectedDayID && $0.isCurrentMonth }) else {
            return nil
        }
        return day.dayNumber
    }

    /// Re-selects a day after month regeneration using ``CalendarEngine`` smart selection.
    private func restoreSelection(preferredDayNumber: Int?) {
        guard let resolution = engine.resolveSelectedDay(
            preferredDay: preferredDayNumber,
            month: displayedMonth,
            year: displayedYear
        ) else {
            selectedDayID = nil
            lastSelectionWasClamped = false
            return
        }

        lastSelectionWasClamped = resolution.wasClamped
        guard let match = baseDays.first(where: {
            $0.isCurrentMonth && $0.dayNumber == resolution.dayNumber
        }) else {
            selectedDayID = nil
            return
        }
        selectedDayID = match.id
    }

    /// Inclusive start / exclusive end covering every cell in the grid.
    private var gridDateInterval: DateInterval {
        guard let first = baseDays.first?.date,
              let last = baseDays.last?.date,
              let end = calendar.date(byAdding: .day, value: 1, to: last)
        else {
            let now = Date()
            return DateInterval(start: now, end: now)
        }

        return DateInterval(start: calendar.startOfDay(for: first), end: end)
    }
}
