//
//  CalendarGridView.swift
//  GalacticCalendar
//

import SwiftUI

/// Approved monthly calendar grid driven exclusively by ``CalendarEngine``.
///
/// Always renders the current month as a fixed 7×6 (42-cell) grid.
/// Each ``CalendarDay`` receives the SwiftData events that belong to its date.
struct CalendarGridView: View {

    // MARK: - Environment

    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    /// Persistence façade used to load events for each day in the grid.
    @Environment(EventPersistenceService.self) private var eventPersistenceService

    // MARK: - Properties

    /// Base days generated by ``CalendarEngine`` (without event annotations).
    private let baseDays: [CalendarDay]

    /// Current month obtained from the engine.
    private let displayedMonth: Int

    /// Current year obtained from the engine.
    private let displayedYear: Int

    /// Calendar used to match events to day starts.
    private let calendar: Calendar

    /// Locally selected day identifier.
    @State private var selectedDayID: String?

    /// Days annotated with events for their dates.
    @State private var days: [CalendarDay]

    /// Called after an in-month day is selected.
    private let onDaySelected: ((CalendarDay) -> Void)?

    // MARK: - Lifecycle

    /// Creates a grid for the engine's current month and year.
    /// - Parameters:
    ///   - engine: Calendar structure generator.
    ///   - calendar: Calendar used for day-boundary matching.
    ///   - onDaySelected: Optional handler invoked with the tapped in-month day.
    init(
        engine: CalendarEngine = CalendarEngine(),
        calendar: Calendar = .current,
        onDaySelected: ((CalendarDay) -> Void)? = nil
    ) {
        let month = engine.currentMonth()
        let year = engine.currentYear()
        let generated = Array(
            engine.generateDays(month: month, year: year)
                .prefix(CalendarConstants.monthlyGridCellCount)
        )

        self.displayedMonth = month
        self.displayedYear = year
        self.calendar = calendar
        self.baseDays = generated
        self.onDaySelected = onDaySelected
        _days = State(initialValue: generated)
    }

    // MARK: - Body

    var body: some View {
        VStack(spacing: gridSpacing) {
            WeekHeaderView()

            LazyVGrid(columns: Self.columns, spacing: gridSpacing) {
                ForEach(days) { day in
                    dayCell(for: day)
                }
            }
            .frame(maxWidth: .infinity)
        }
        .accessibilityElement(children: .contain)
        .accessibilityLabel(Text("\(displayedMonth)/\(displayedYear)"))
        .task(id: eventPersistenceService.eventsRevision) {
            await loadEventsForDays()
        }
    }

    // MARK: - Cells

    @ViewBuilder
    private func dayCell(for day: CalendarDay) -> some View {
        CalendarDayCell(day: applyingSelection(to: day))
            .contentShape(Rectangle())
            .onTapGesture {
                selectDay(day)
            }
    }

    // MARK: - Selection

    private func selectDay(_ day: CalendarDay) {
        guard day.isCurrentMonth else { return }
        selectedDayID = day.id
        onDaySelected?(day)
    }

    private func applyingSelection(to day: CalendarDay) -> CalendarDay {
        var presented = day
        presented.isSelected = (day.id == selectedDayID)
        return presented
    }

    // MARK: - Events

    /// Loads SwiftData events for the visible grid and annotates each ``CalendarDay``.
    private func loadEventsForDays() async {
        guard let interval = gridDateInterval else {
            days = baseDays
            return
        }

        do {
            let grouped = try await eventPersistenceService.fetchGroupedByDay(in: interval)
            days = baseDays.map { day in
                day.applyingEvents(events(for: day, in: grouped))
            }
        } catch {
            days = baseDays
        }
    }

    /// Returns events stored for a single calendar day.
    private func events(for day: CalendarDay, in grouped: [Date: [Event]]) -> [Event] {
        let dayStart = calendar.startOfDay(for: day.date)
        return grouped[dayStart] ?? []
    }

    /// Inclusive start / exclusive end covering every cell in the grid.
    private var gridDateInterval: DateInterval? {
        guard let first = baseDays.first?.date,
              let last = baseDays.last?.date,
              let end = calendar.date(byAdding: .day, value: 1, to: last)
        else {
            return nil
        }

        return DateInterval(start: calendar.startOfDay(for: first), end: end)
    }

    // MARK: - Grid

    private static let columns: [GridItem] = Array(
        repeating: GridItem(.flexible(), spacing: Spacing.xxs),
        count: CalendarConstants.columnCount
    )

    private var gridSpacing: CGFloat {
        horizontalSizeClass == .regular ? Spacing.xs : Spacing.xxs
    }
}

// MARK: - Previews

#if DEBUG
#Preview("Calendar Grid — Current Month") {
    ZStack {
        MonthBackgroundView()
        CalendarGridView()
            .padding(.horizontal, Spacing.pageHorizontal)
    }
    .environment(ThemeManager())
    .environment(
        EventPersistenceService(
            repository: PreviewGridEventRepository()
        )
    )
}

@MainActor
private final class PreviewGridEventRepository: EventRepositoryProtocol {

    func create(_ event: Event) async throws {}

    func fetchAll() async throws -> [Event] { [] }

    func fetch(by id: UUID) async throws -> Event? { nil }

    func fetch(on date: Date) async throws -> [Event] { [] }

    func fetch(in interval: DateInterval) async throws -> [Event] { [] }

    func fetchGroupedByDay(in interval: DateInterval) async throws -> [Date: [Event]] { [:] }

    func update(_ event: Event) async throws {}

    func delete(_ event: Event) async throws {}

    func delete(id: UUID) async throws {}

    func duplicate(_ event: Event) async throws -> Event { event.duplicated() }
}
#endif
